import { prisma } from "@/lib/db"

export const DEFAULT_PROMPT_ANALYSE_NEW_FILE = `You are an expert accountant specialized in document analysis. Your task is to extract ALL available information from the given document. The document can be an invoice, receipt, expense report, or any financial document.

Extract the following fields:

{fields}

Also extract "items": every separate product, service, or line item listed in the document (even if there is only one).

Categories available:
{categories}

Projects available:
{projects}

IMPORTANT RULES:
- Extract EVERY piece of information visible in the document — do not skip fields if the data is present
- For dates, always use YYYY-MM-DD format
- For amounts, always use numbers without currency symbols
- If a field is truly not present in the document, leave it as an empty string — NEVER invent or guess data
- Detect the document language and extract merchant/vendor names in their original spelling
- For expense reports: treat each expense line as a separate item
- For receipts: extract the store/vendor, each purchased item, subtotal, taxes, and total separately
- Return only one valid JSON object, no explanation, no markdown`

export const DEFAULT_SETTINGS = [
  {
    code: "default_currency",
    name: "Default Currency",
    description: "Don't change this setting if you already have multi-currency transactions. I won't recalculate them.",
    value: "EUR",
  },
  {
    code: "default_category",
    name: "Default Category",
    description: "",
    value: "other",
  },
  {
    code: "default_project",
    name: "Default Project",
    description: "",
    value: "personal",
  },
  {
    code: "default_type",
    name: "Default Type",
    description: "",
    value: "expense",
  },
  {
    code: "prompt_analyse_new_file",
    name: "Prompt for Analyze Transaction",
    description: "Allowed variables: {fields}, {categories}, {categories.code}, {projects}, {projects.code}",
    value: DEFAULT_PROMPT_ANALYSE_NEW_FILE,
  },
  {
    code: "is_welcome_message_hidden",
    name: "Do not show welcome message on dashboard",
    description: "",
    value: "false",
  },
]

export const DEFAULT_CATEGORIES = [
  { code: "ads", name: "Advertisement", color: "#882727", llm_prompt: "ads, promos, online ads, marketing" },
  { code: "swag", name: "Swag and Goods", color: "#882727", llm_prompt: "swag, stickers, branded goods, merchandise" },
  { code: "donations", name: "Gifts and Donations", color: "#1e6359", llm_prompt: "donations, gifts, charity, sponsorship" },
  { code: "tools", name: "Equipment and Tools", color: "#c69713", llm_prompt: "equipment, tools, hardware, devices" },
  { code: "events", name: "Events and Conferences", color: "#ff8b32", llm_prompt: "events, conferences, seminars, workshops" },
  { code: "food", name: "Food and Drinks", color: "#d40e70", llm_prompt: "food, drinks, restaurant, business meals, cafeteria" },
  { code: "insurance", name: "Insurance", color: "#050942", llm_prompt: "insurance, health, life, vehicle insurance" },
  { code: "invoice", name: "Invoice", color: "#064e85", llm_prompt: "custom invoice, bill, service invoice" },
  { code: "communication", name: "Mobile and Internet", color: "#0e7d86", llm_prompt: "mobile, internet, phone, telecom, data plan" },
  { code: "office", name: "Office Supplies", color: "#59b0b9", llm_prompt: "office, supplies, stationery, printer, paper" },
  { code: "online", name: "Online Services", color: "#8753fb", llm_prompt: "online services, saas, subscriptions, cloud" },
  { code: "rental", name: "Rental", color: "#050942", llm_prompt: "rental, lease, coworking, workspace" },
  { code: "education", name: "Education", color: "#ee5d6c", llm_prompt: "education, professional development, trainings, courses, books" },
  { code: "salary", name: "Salary", color: "#ce4993", llm_prompt: "salary, wages, payroll, contractor payment" },
  { code: "fees", name: "Fees", color: "#6a0d83", llm_prompt: "fees, charges, penalties, bank fees, late fees" },
  { code: "travel", name: "Travel Expenses", color: "#fb9062", llm_prompt: "travel, accommodation, hotel, flight, airbnb, transport reimbursement" },
  { code: "utility_bills", name: "Utility Bills", color: "#af7e2e", llm_prompt: "bills, electricity, water, gas, utilities" },
  { code: "transport", name: "Transport", color: "#800000", llm_prompt: "transportation, fuel, taxi, uber, car rental, parking, toll, vignette" },
  { code: "software", name: "Software", color: "#2b5a1d", llm_prompt: "software, licenses, apps, digital tools" },
  { code: "healthcare", name: "Healthcare", color: "#c0392b", llm_prompt: "medical, doctor, pharmacy, hospital, health expenses" },
  { code: "other", name: "Other", color: "#121216", llm_prompt: "other, miscellaneous, unclassified" },
]

export const DEFAULT_PROJECTS = [
  { code: "personal", name: "Personal", llm_prompt: "personal expense", color: "#1e202b" },
]

export const DEFAULT_CURRENCIES = [
  { code: "USD", name: "$" },
  { code: "EUR", name: "€" },
  { code: "GBP", name: "£" },
  { code: "INR", name: "₹" },
  { code: "AUD", name: "$" },
  { code: "CAD", name: "$" },
  { code: "SGD", name: "$" },
  { code: "CHF", name: "Fr" },
  { code: "MYR", name: "RM" },
  { code: "JPY", name: "¥" },
  { code: "CNY", name: "¥" },
  { code: "NZD", name: "$" },
  { code: "THB", name: "฿" },
  { code: "HUF", name: "Ft" },
  { code: "AED", name: "د.إ" },
  { code: "HKD", name: "$" },
  { code: "MXN", name: "$" },
  { code: "ZAR", name: "R" },
  { code: "PHP", name: "₱" },
  { code: "SEK", name: "kr" },
  { code: "IDR", name: "Rp" },
  { code: "BRL", name: "R$" },
  { code: "SAR", name: "﷼" },
  { code: "TRY", name: "₺" },
  { code: "KES", name: "KSh" },
  { code: "KRW", name: "₩" },
  { code: "EGP", name: "£" },
  { code: "IQD", name: "ع.د" },
  { code: "NOK", name: "kr" },
  { code: "KWD", name: "د.ك" },
  { code: "RUB", name: "₽" },
  { code: "DKK", name: "kr" },
  { code: "PKR", name: "₨" },
  { code: "ILS", name: "₪" },
  { code: "PLN", name: "zł" },
  { code: "QAR", name: "﷼" },
  { code: "MAD", name: "د.م." },
  { code: "UAH", name: "₴" },
  { code: "NGN", name: "₦" },
  { code: "RON", name: "lei" },
  { code: "BDT", name: "৳" },
  { code: "PEN", name: "S/" },
  { code: "GEL", name: "₾" },
  { code: "KZT", name: "₸" },
  { code: "AZN", name: "₼" },
  { code: "AMD", name: "֏" },
  { code: "BTC", name: "Crypto" },
  { code: "ETH", name: "Crypto" },
  { code: "USDT", name: "Crypto" },
]

export const DEFAULT_FIELDS = [
  // ── Core identification ──────────────────────────────────────────────────
  {
    code: "name",
    name: "Name",
    type: "string",
    llm_prompt: "human readable name summarizing what is bought, paid for, or reimbursed",
    isVisibleInList: true,
    isVisibleInAnalysis: true,
    isRequired: true,
    isExtra: false,
  },
  {
    code: "description",
    name: "Description",
    type: "string",
    llm_prompt: "full description of the transaction or service rendered",
    isVisibleInList: false,
    isVisibleInAnalysis: true,
    isRequired: false,
    isExtra: false,
  },
  {
    code: "document_type",
    name: "Document Type",
    type: "string",
    llm_prompt: "type of document: invoice, receipt, expense_report, credit_note, proforma, quote, purchase_order, bill, statement",
    isVisibleInList: true,
    isVisibleInAnalysis: true,
    isRequired: false,
    isExtra: false,
  },
  {
    code: "invoice_number",
    name: "Invoice / Receipt Number",
    type: "string",
    llm_prompt: "invoice number, receipt number, bill number, or document reference ID",
    isVisibleInList: true,
    isVisibleInAnalysis: true,
    isRequired: false,
    isExtra: false,
  },
  {
    code: "reference_number",
    name: "Reference Number",
    type: "string",
    llm_prompt: "purchase order, transaction reference, or internal reference number",
    isVisibleInList: false,
    isVisibleInAnalysis: false,
    isRequired: false,
    isExtra: false,
  },

  // ── Parties ──────────────────────────────────────────────────────────────
  {
    code: "merchant",
    name: "Merchant / Vendor",
    type: "string",
    llm_prompt: "merchant, vendor, supplier, or service provider name in original spelling and language",
    isVisibleInList: true,
    isVisibleInAnalysis: true,
    isRequired: false,
    isExtra: false,
  },
  {
    code: "merchant_email",
    name: "Merchant Email",
    type: "string",
    llm_prompt: "email address of the merchant or vendor",
    isVisibleInList: false,
    isVisibleInAnalysis: false,
    isRequired: false,
    isExtra: false,
  },
  {
    code: "merchant_phone",
    name: "Merchant Phone",
    type: "string",
    llm_prompt: "phone number of the merchant or vendor",
    isVisibleInList: false,
    isVisibleInAnalysis: false,
    isRequired: false,
    isExtra: false,
  },
  {
    code: "merchant_address",
    name: "Merchant Address",
    type: "string",
    llm_prompt: "full address of the merchant, vendor, or service provider",
    isVisibleInList: false,
    isVisibleInAnalysis: false,
    isRequired: false,
    isExtra: false,
  },
  {
    code: "merchant_tax_id",
    name: "Merchant Tax ID",
    type: "string",
    llm_prompt: "tax ID, VAT number, SIRET, business registration number, or company ID of the merchant",
    isVisibleInList: false,
    isVisibleInAnalysis: false,
    isRequired: false,
    isExtra: false,
  },
  {
    code: "client_name",
    name: "Client / Buyer Name",
    type: "string",
    llm_prompt: "name of the client, buyer, customer, or person being billed",
    isVisibleInList: false,
    isVisibleInAnalysis: false,
    isRequired: false,
    isExtra: false,
  },
  {
    code: "client_email",
    name: "Client Email",
    type: "string",
    llm_prompt: "email address of the client or buyer",
    isVisibleInList: false,
    isVisibleInAnalysis: false,
    isRequired: false,
    isExtra: false,
  },
  {
    code: "client_address",
    name: "Client Address",
    type: "string",
    llm_prompt: "full address of the client or buyer",
    isVisibleInList: false,
    isVisibleInAnalysis: false,
    isRequired: false,
    isExtra: false,
  },
  {
    code: "client_tax_id",
    name: "Client Tax ID",
    type: "string",
    llm_prompt: "tax ID, VAT number, or business registration number of the client",
    isVisibleInList: false,
    isVisibleInAnalysis: false,
    isRequired: false,
    isExtra: false,
  },

  // ── Dates ────────────────────────────────────────────────────────────────
  {
    code: "issuedAt",
    name: "Issued At",
    type: "string",
    llm_prompt: "document issue date (YYYY-MM-DD format)",
    isVisibleInList: true,
    isVisibleInAnalysis: true,
    isRequired: true,
    isExtra: false,
  },
  {
    code: "due_date",
    name: "Due Date",
    type: "string",
    llm_prompt: "payment due date, expiry date, or deadline (YYYY-MM-DD format)",
    isVisibleInList: true,
    isVisibleInAnalysis: true,
    isRequired: false,
    isExtra: false,
  },
  {
    code: "delivery_date",
    name: "Delivery Date",
    type: "string",
    llm_prompt: "expected delivery or service completion date (YYYY-MM-DD format)",
    isVisibleInList: false,
    isVisibleInAnalysis: false,
    isRequired: false,
    isExtra: false,
  },

  // ── Amounts ──────────────────────────────────────────────────────────────
  {
    code: "subtotal",
    name: "Subtotal (before tax)",
    type: "number",
    llm_prompt: "subtotal amount before taxes, VAT, or discounts",
    isVisibleInList: false,
    isVisibleInAnalysis: true,
    isRequired: false,
    isExtra: false,
  },
  {
    code: "discount_amount",
    name: "Discount Amount",
    type: "number",
    llm_prompt: "total discount amount applied as a number",
    isVisibleInList: false,
    isVisibleInAnalysis: true,
    isRequired: false,
    isExtra: false,
  },
  {
    code: "discount_percentage",
    name: "Discount Percentage (%)",
    type: "number",
    llm_prompt: "discount percentage applied (0–100)",
    isVisibleInList: false,
    isVisibleInAnalysis: false,
    isRequired: false,
    isExtra: false,
  },
  {
    code: "discount_reason",
    name: "Discount Reason",
    type: "string",
    llm_prompt: "reason for discount (early payment, loyalty, promotional, etc.)",
    isVisibleInList: false,
    isVisibleInAnalysis: false,
    isRequired: false,
    isExtra: false,
  },
  {
    code: "shipping_amount",
    name: "Shipping / Delivery Cost",
    type: "number",
    llm_prompt: "shipping, delivery, or transportation cost",
    isVisibleInList: false,
    isVisibleInAnalysis: true,
    isRequired: false,
    isExtra: false,
  },
  {
    code: "handling_amount",
    name: "Handling / Processing Fee",
    type: "number",
    llm_prompt: "handling, processing, or service fee",
    isVisibleInList: false,
    isVisibleInAnalysis: false,
    isRequired: false,
    isExtra: false,
  },
  {
    code: "vat_rate",
    name: "VAT Rate (%)",
    type: "number",
    llm_prompt: "VAT, tax, or sales tax rate as a percentage (0–100)",
    isVisibleInList: false,
    isVisibleInAnalysis: true,
    isRequired: false,
    isExtra: false,
  },
  {
    code: "vat",
    name: "VAT / Tax Amount",
    type: "number",
    llm_prompt: "total VAT, sales tax, or tax amount in the invoice currency",
    isVisibleInList: false,
    isVisibleInAnalysis: true,
    isRequired: false,
    isExtra: false,
  },
  {
    code: "total",
    name: "Total",
    type: "number",
    llm_prompt: "final total amount of the transaction including all taxes and fees",
    isVisibleInList: true,
    isVisibleInAnalysis: true,
    isRequired: true,
    isExtra: false,
  },
  {
    code: "currencyCode",
    name: "Currency",
    type: "string",
    llm_prompt: "currency code, ISO 4217 three-letter code (USD, EUR, MAD…) or crypto code (BTC, ETH…)",
    isVisibleInList: true,
    isVisibleInAnalysis: true,
    isRequired: false,
    isExtra: false,
  },
  {
    code: "convertedTotal",
    name: "Converted Total",
    type: "number",
    llm_prompt: "transaction total converted to user's default currency",
    isVisibleInList: false,
    isVisibleInAnalysis: true,
    isRequired: false,
    isExtra: false,
  },
  {
    code: "convertedCurrencyCode",
    name: "Converted Currency Code",
    type: "string",
    llm_prompt: "currency code of the converted total (ISO 4217 format)",
    isVisibleInList: false,
    isVisibleInAnalysis: false,
    isRequired: false,
    isExtra: false,
  },
  {
    code: "exchange_rate",
    name: "Exchange Rate",
    type: "number",
    llm_prompt: "exchange rate used for currency conversion",
    isVisibleInList: false,
    isVisibleInAnalysis: false,
    isRequired: false,
    isExtra: false,
  },

  // ── Line Items ───────────────────────────────────────────────────────────
  {
    code: "items",
    name: "Line Items",
    type: "json",
    llm_prompt: "extract every separate product, service, or line item as a JSON array with fields: description, quantity, unit_price, total, category (optional), vat_rate (optional)",
    isVisibleInList: true,
    isVisibleInAnalysis: true,
    isRequired: false,
    isExtra: false,
  },
  {
    code: "item_description",
    name: "Item Description",
    type: "string",
    llm_prompt: "description of product, service, or line item",
    isVisibleInList: true,
    isVisibleInAnalysis: true,
    isRequired: false,
    isExtra: false,
  },
  {
    code: "item_quantity",
    name: "Item Quantity",
    type: "number",
    llm_prompt: "quantity or count of the item",
    isVisibleInList: true,
    isVisibleInAnalysis: true,
    isRequired: false,
    isExtra: false,
  },
  {
    code: "item_unit",
    name: "Item Unit",
    type: "string",
    llm_prompt: "unit of measurement (pieces, hours, kg, m, etc.)",
    isVisibleInList: false,
    isVisibleInAnalysis: false,
    isRequired: false,
    isExtra: false,
  },
  {
    code: "item_unit_price",
    name: "Item Unit Price",
    type: "number",
    llm_prompt: "unit price or rate per item",
    isVisibleInList: true,
    isVisibleInAnalysis: true,
    isRequired: false,
    isExtra: false,
  },
  {
    code: "item_total",
    name: "Item Total",
    type: "number",
    llm_prompt: "total amount for this line item (quantity × unit_price)",
    isVisibleInList: true,
    isVisibleInAnalysis: true,
    isRequired: false,
    isExtra: false,
  },

  // ── Payment ──────────────────────────────────────────────────────────────
  {
    code: "payment_method",
    name: "Payment Method",
    type: "string",
    llm_prompt: "payment method: cash, credit_card, debit_card, bank_transfer, check, paypal, cryptocurrency, mobile_wallet, or other",
    isVisibleInList: false,
    isVisibleInAnalysis: true,
    isRequired: false,
    isExtra: false,
  },
  {
    code: "payment_status",
    name: "Payment Status",
    type: "string",
    llm_prompt: "payment status: paid, pending, overdue, partial, cancelled, or refunded",
    isVisibleInList: false,
    isVisibleInAnalysis: true,
    isRequired: false,
    isExtra: false,
  },
  {
    code: "payment_reference",
    name: "Payment Reference",
    type: "string",
    llm_prompt: "transaction ID, confirmation number, or payment reference",
    isVisibleInList: false,
    isVisibleInAnalysis: false,
    isRequired: false,
    isExtra: false,
  },
  {
    code: "iban",
    name: "IBAN",
    type: "string",
    llm_prompt: "IBAN or bank account number if present on the document",
    isVisibleInList: false,
    isVisibleInAnalysis: false,
    isRequired: false,
    isExtra: false,
  },
  {
    code: "bank_name",
    name: "Bank Name",
    type: "string",
    llm_prompt: "bank or financial institution name",
    isVisibleInList: false,
    isVisibleInAnalysis: false,
    isRequired: false,
    isExtra: false,
  },
  {
    code: "swift_code",
    name: "SWIFT / BIC Code",
    type: "string",
    llm_prompt: "SWIFT code or BIC number for international transfers",
    isVisibleInList: false,
    isVisibleInAnalysis: false,
    isRequired: false,
    isExtra: false,
  },

  // ── Classification ───────────────────────────────────────────────────────
  {
    code: "type",
    name: "Type",
    type: "string",
    llm_prompt: "transaction type: expense, income, refund, transfer, reimbursement, or credit",
    isVisibleInList: false,
    isVisibleInAnalysis: true,
    isRequired: false,
    isExtra: false,
  },
  {
    code: "categoryCode",
    name: "Category",
    type: "string",
    llm_prompt: "category code, one of: {categories.code}",
    isVisibleInList: true,
    isVisibleInAnalysis: true,
    isRequired: false,
    isExtra: false,
  },
  {
    code: "projectCode",
    name: "Project",
    type: "string",
    llm_prompt: "project code, one of: {projects.code}",
    isVisibleInList: true,
    isVisibleInAnalysis: true,
    isRequired: false,
    isExtra: false,
  },
  {
    code: "department",
    name: "Department",
    type: "string",
    llm_prompt: "department, team, or cost center associated with the transaction",
    isVisibleInList: false,
    isVisibleInAnalysis: true,
    isRequired: false,
    isExtra: false,
  },
  {
    code: "tags",
    name: "Tags",
    type: "string",
    llm_prompt: "comma-separated tags or labels for categorization",
    isVisibleInList: false,
    isVisibleInAnalysis: false,
    isRequired: false,
    isExtra: false,
  },

  // ── Additional Details ───────────────────────────────────────────────────
  {
    code: "terms_and_conditions",
    name: "Terms & Conditions",
    type: "string",
    llm_prompt: "payment terms, conditions, or notes from the document",
    isVisibleInList: false,
    isVisibleInAnalysis: false,
    isRequired: false,
    isExtra: false,
  },
  {
    code: "shipping_address",
    name: "Shipping Address",
    type: "string",
    llm_prompt: "delivery or shipping address if different from client address",
    isVisibleInList: false,
    isVisibleInAnalysis: false,
    isRequired: false,
    isExtra: false,
  },
  {
    code: "tracking_number",
    name: "Tracking Number",
    type: "string",
    llm_prompt: "shipping, delivery, or parcel tracking number",
    isVisibleInList: false,
    isVisibleInAnalysis: false,
    isRequired: false,
    isExtra: false,
  },
  {
    code: "warranty_info",
    name: "Warranty Information",
    type: "string",
    llm_prompt: "warranty period or coverage details if provided",
    isVisibleInList: false,
    isVisibleInAnalysis: false,
    isRequired: false,
    isExtra: false,
  },
  {
    code: "company_name",
    name: "Company / Organization Name",
    type: "string",
    llm_prompt: "company or organization name from the document header",
    isVisibleInList: false,
    isVisibleInAnalysis: true,
    isRequired: false,
    isExtra: false,
  },

  // ── Meta ─────────────────────────────────────────────────────────────────
  {
    code: "files",
    name: "Files",
    type: "string",
    llm_prompt: "file names or references attached to the transaction",
    isVisibleInList: true,
    isVisibleInAnalysis: true,
    isRequired: false,
    isExtra: false,
  },
  {
    code: "note",
    name: "Note",
    type: "string",
    llm_prompt: "user notes or comments about the transaction",
    isVisibleInList: false,
    isVisibleInAnalysis: false,
    isRequired: false,
    isExtra: false,
  },
  {
    code: "text",
    name: "Extracted Text",
    type: "string",
    llm_prompt: "extract ALL raw text visible in the document exactly as written",
    isVisibleInList: false,
    isVisibleInAnalysis: false,
    isRequired: false,
    isExtra: false,
  },
  {
    code: "confidence",
    name: "Extraction Confidence",
    type: "string",
    llm_prompt: "confidence level of the extracted data: high, medium, low",
    isVisibleInList: false,
    isVisibleInAnalysis: false,
    isRequired: false,
    isExtra: false,
  },
]

export async function createUserDefaults(userId: string) {
  for (const project of DEFAULT_PROJECTS) {
    await prisma.project.upsert({
      where: { userId_code: { code: project.code, userId } },
      update: { name: project.name, color: project.color, llm_prompt: project.llm_prompt },
      create: { ...project, userId },
    })
  }

  for (const category of DEFAULT_CATEGORIES) {
    await prisma.category.upsert({
      where: { userId_code: { code: category.code, userId } },
      update: { name: category.name, color: category.color, llm_prompt: category.llm_prompt },
      create: { ...category, userId },
    })
  }

  for (const currency of DEFAULT_CURRENCIES) {
    await prisma.currency.upsert({
      where: { userId_code: { code: currency.code, userId } },
      update: { name: currency.name },
      create: { ...currency, userId },
    })
  }

  for (const field of DEFAULT_FIELDS) {
    await prisma.field.upsert({
      where: { userId_code: { code: field.code, userId } },
      update: {
        name: field.name,
        type: field.type,
        llm_prompt: field.llm_prompt,
        isVisibleInList: field.isVisibleInList,
        isVisibleInAnalysis: field.isVisibleInAnalysis,
        isRequired: field.isRequired,
        isExtra: field.isExtra,
      },
      create: { ...field, userId },
    })
  }

  for (const setting of DEFAULT_SETTINGS) {
    await prisma.setting.upsert({
      where: { userId_code: { code: setting.code, userId } },
      update: { name: setting.name, description: setting.description, value: setting.value },
      create: { ...setting, userId },
    })
  }
}

export async function isDatabaseEmpty(userId: string) {
  const fieldsCount = await prisma.field.count({ where: { userId } })
  return fieldsCount === 0
}